"""Execution-domain models: executions, attempts, log-file index, artifacts.

Identity: ``execution_id`` and ``attempt_id`` are opaque 32-char uuid hex
strings generated by the server. They travel to the agent (run/status/tail/
cleanup) and into the on-disk log path, so they are kept as plain strings (not
DB-native UUID) to be identical on the wire, in the filesystem, and in the DB.

JSON columns use ``JSONB`` on PostgreSQL and fall back to ``JSON`` on SQLite
(tests), mirroring :class:`dopilot_server.models.node.Node`.
"""

from __future__ import annotations

import uuid
from datetime import datetime

from sqlalchemy import JSON, BigInteger, DateTime, ForeignKey, Integer, String, func
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import Mapped, mapped_column

from ..db.base import Base

_JSON = JSON().with_variant(JSONB(), "postgresql")


def _new_id() -> str:
    return uuid.uuid4().hex


class Execution(Base):
    """One logical run dispatched to one or more target nodes (attempts)."""

    __tablename__ = "executions"

    id: Mapped[str] = mapped_column(String(32), primary_key=True, default=_new_id)
    task_type: Mapped[str] = mapped_column(String, nullable=False)
    target: Mapped[str] = mapped_column(String, nullable=False, default="")
    node_strategy: Mapped[str] = mapped_column(
        String, nullable=False, default="all"
    )
    # queued | running | finalizing | complete | failed | canceled | lost
    status: Mapped[str] = mapped_column(
        String, nullable=False, default="queued"
    )
    params: Mapped[dict] = mapped_column(_JSON, nullable=False, default=dict)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    started_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    finished_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )


class ExecutionAttempt(Base):
    """One attempt of an execution on a single target node."""

    __tablename__ = "execution_attempts"

    id: Mapped[str] = mapped_column(String(32), primary_key=True, default=_new_id)
    execution_id: Mapped[str] = mapped_column(
        String(32), ForeignKey("executions.id"), nullable=False, index=True
    )
    agent_id: Mapped[str | None] = mapped_column(String, nullable=True)
    node_id: Mapped[str | None] = mapped_column(String, nullable=True)
    endpoint: Mapped[str | None] = mapped_column(String, nullable=True)
    remote_job_id: Mapped[str | None] = mapped_column(String, nullable=True)
    # pending | running | finished | failed | canceled | lost
    status: Mapped[str] = mapped_column(
        String, nullable=False, default="pending"
    )
    started_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    finished_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    exit_code: Mapped[int | None] = mapped_column(Integer, nullable=True)
    error_code: Mapped[str | None] = mapped_column(String, nullable=True)
    error_detail: Mapped[dict] = mapped_column(_JSON, nullable=False, default=dict)
    # Phase 1.5: set to "lost" when an agent-authoritative terminal overrides a
    # prior server-inferred lost (audit of the soft-terminal override).
    reconciled_from: Mapped[str | None] = mapped_column(String, nullable=True)
    # Why the attempt was declared lost: server-inferred (heartbeat_timeout /
    # event_stall) or agent-reported (state_missing / process_missing /
    # runner_recovered_unknown / spawn_aborted).
    lost_reason: Mapped[str | None] = mapped_column(String, nullable=True)
    # Event-stall clock: last time a status event for this attempt was applied
    # (restart-survivable; the reconcile loop reads it, decoupled from updated_at).
    last_event_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    # One-shot stalled-alert marker (operator-visible; NOT a terminal state;
    # cleared when the next event arrives).
    stalled_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )


class ExecutionLogFile(Base):
    """Log index/offset/status row. Bodies live on disk, NOT in PostgreSQL.

    Primary key is ``(execution_id, attempt_id, stream)`` per the v1 spec.
    """

    __tablename__ = "execution_log_files"

    execution_id: Mapped[str] = mapped_column(String(32), primary_key=True)
    attempt_id: Mapped[str] = mapped_column(String(32), primary_key=True)
    # log | stdout | stderr | system (scrapy only produces "log")
    stream: Mapped[str] = mapped_column(
        String, primary_key=True, default="log"
    )
    storage_path: Mapped[str] = mapped_column(String, nullable=False)
    size_bytes: Mapped[int] = mapped_column(
        BigInteger, nullable=False, default=0
    )
    last_pulled_offset: Mapped[int] = mapped_column(
        BigInteger, nullable=False, default=0
    )
    # final_offset = server file PHYSICAL size (incl. visible gap markers);
    # agent logical consumption progress lives in last_pulled_offset (never mix).
    final_offset: Mapped[int | None] = mapped_column(BigInteger, nullable=True)
    # active | finalizing | complete | missing | expired  (log LIFECYCLE)
    status: Mapped[str] = mapped_column(
        String, nullable=False, default="active"
    )
    # Phase 1.5: log COMPLETENESS, decoupled from lifecycle status. Sticky:
    # once "partial" (a gap was seen), it never reverts to "complete".
    # complete | partial | missing | expired
    log_integrity: Mapped[str] = mapped_column(
        String, nullable=False, default="complete"
    )
    gap_count: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    first_gap_expected_offset: Mapped[int | None] = mapped_column(
        BigInteger, nullable=True
    )
    first_gap_actual_offset: Mapped[int | None] = mapped_column(
        BigInteger, nullable=True
    )
    started_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    finished_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    retained_until: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )


class ScrapyArtifact(Base):
    """A deployed (uploaded) Scrapy egg and where it was deployed."""

    __tablename__ = "scrapy_artifacts"

    id: Mapped[str] = mapped_column(String(32), primary_key=True, default=_new_id)
    project: Mapped[str] = mapped_column(String, nullable=False)
    version: Mapped[str] = mapped_column(String, nullable=False)
    filename: Mapped[str] = mapped_column(String, nullable=False)
    sha256: Mapped[str] = mapped_column(String, nullable=False)
    size_bytes: Mapped[int] = mapped_column(
        BigInteger, nullable=False, default=0
    )
    agent_id: Mapped[str | None] = mapped_column(String, nullable=True)
    endpoint: Mapped[str | None] = mapped_column(String, nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
