"""Execution-domain models: tasks, executions, log-file index, artifacts.

Phase 1.7 domain split (parent/atomic, inverted from the phase-1.5 names):

- :class:`Task` — the parent logical run (table ``tasks``; was ``executions``).
- :class:`Execution` — the atomic per-node unit (table ``executions``; was
  ``execution_attempts``). Its FK to the parent is ``task_id``.

Wire/disk/agent ids (phase 2a clean-cut). The Redis stream payloads, the on-disk
log path, and the agent state files now use the same names as the domain:
``task_id`` (= :class:`Task` id) and ``execution_id`` (= :class:`Execution` id).
The seam tables :class:`ExecutionLogFile` (and ``command_outbox`` /
``event_audit``) carry the columns ``task_id`` / ``execution_id`` directly — there
is no boundary translation anymore. See :mod:`dopilot_protocol.streams`.

Identity: ids are opaque 32-char uuid hex strings generated by the server. They
travel to the agent and into the on-disk log path, so they are kept as plain
strings (not DB-native UUID) to be identical on the wire, in the filesystem,
and in the DB.

JSON columns use ``JSONB`` on PostgreSQL and fall back to ``JSON`` on SQLite
(tests), mirroring :class:`dopilot_server.models.node.Node`.
"""

from __future__ import annotations

import uuid
from datetime import datetime

from sqlalchemy import (
    JSON,
    BigInteger,
    DateTime,
    ForeignKey,
    Integer,
    String,
    UniqueConstraint,
    func,
)
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import Mapped, mapped_column

from ..db.base import Base

_JSON = JSON().with_variant(JSONB(), "postgresql")


def _new_id() -> str:
    return uuid.uuid4().hex


class Task(Base):
    """One parent logical run, fanned out to one execution per target node."""

    __tablename__ = "tasks"

    id: Mapped[str] = mapped_column(String(32), primary_key=True, default=_new_id)
    # Phase 1.8: the RESOLVED build-artifact type of this run (scrapy | reserved
    # python_wheel | docker_image). This is the core-domain discriminator (it
    # replaced the misleading ``task_type``); the wire ``task_type`` survives
    # only in the Redis command payload, translated at the dispatcher boundary.
    artifact_type: Mapped[str] = mapped_column(String, nullable=False)
    target: Mapped[str] = mapped_column(String, nullable=False, default="")
    node_strategy: Mapped[str] = mapped_column(
        String, nullable=False, default="all"
    )
    # Phase 1.7.1: the Scrapy spider of this run, copied from the parsed run
    # params at creation time. A queryable/indexed task-level value backs the
    # execution-list spider filter at large history volume (avoids scanning the
    # ``params`` JSON). NULL for non-scrapy or spider-less runs.
    spider: Mapped[str | None] = mapped_column(String, nullable=True, index=True)
    # Phase 1.7 packet 2 / 1.8: provenance + the immutable resolved snapshot.
    # source: direct_artifact | template | schedule_trigger_now | schedule_timer
    # (legacy rows may carry ``manual``). execution_template_id / schedule_id are
    # NULL for an ad-hoc direct artifact run. template_snapshot is the resolved
    # run snapshot (build artifact + params + node strategy/ids) copied at
    # creation time — editing the template later never mutates this row.
    source: Mapped[str] = mapped_column(
        String, nullable=False, default="direct_artifact"
    )
    execution_template_id: Mapped[str | None] = mapped_column(
        String(32), nullable=True
    )
    schedule_id: Mapped[str | None] = mapped_column(String(32), nullable=True)
    template_snapshot: Mapped[dict] = mapped_column(
        _JSON, nullable=False, default=dict
    )
    # queued | running | finalizing | complete | failed | canceled | lost |
    # no_target
    status: Mapped[str] = mapped_column(
        String, nullable=False, default="queued"
    )
    # Phase 1.7: why a task reached a non-business terminal it cannot explain via
    # a child execution — currently the zero-node `no_target` case. ``reason`` is
    # a short stable code (e.g. "no_target"); ``detail`` is structured context
    # (e.g. {"node_strategy": ..., "healthy_count": 0}). NULL on normal runs.
    status_reason: Mapped[str | None] = mapped_column(String, nullable=True)
    status_detail: Mapped[dict] = mapped_column(_JSON, nullable=False, default=dict)
    params: Mapped[dict] = mapped_column(_JSON, nullable=False, default=dict)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    started_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    finished_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )


class Execution(Base):
    """One atomic execution of a task on a single target node.

    This is the agent's idempotency unit; on the Redis/disk/agent wire it is
    called ``execution_id``. ``task_id`` is the parent :class:`Task`.
    """

    __tablename__ = "executions"

    id: Mapped[str] = mapped_column(String(32), primary_key=True, default=_new_id)
    task_id: Mapped[str] = mapped_column(
        String(32), ForeignKey("tasks.id"), nullable=False, index=True
    )
    agent_id: Mapped[str | None] = mapped_column(String, nullable=True)
    node_id: Mapped[str | None] = mapped_column(String, nullable=True)
    endpoint: Mapped[str | None] = mapped_column(String, nullable=True)
    remote_job_id: Mapped[str | None] = mapped_column(String, nullable=True)
    # pending | running | finished | failed | canceled | lost
    status: Mapped[str] = mapped_column(
        String, nullable=False, default="pending"
    )
    started_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    finished_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    exit_code: Mapped[int | None] = mapped_column(Integer, nullable=True)
    error_code: Mapped[str | None] = mapped_column(String, nullable=True)
    error_detail: Mapped[dict] = mapped_column(_JSON, nullable=False, default=dict)
    # Phase 1.5: set to "lost" when an agent-authoritative terminal overrides a
    # prior server-inferred lost (audit of the soft-terminal override).
    reconciled_from: Mapped[str | None] = mapped_column(String, nullable=True)
    # Why the attempt was declared lost: server-inferred (heartbeat_timeout /
    # event_stall) or agent-reported (state_missing / process_missing /
    # runner_recovered_unknown / spawn_aborted).
    lost_reason: Mapped[str | None] = mapped_column(String, nullable=True)
    # Event-stall clock: last time a status event for this attempt was applied
    # (restart-survivable; the reconcile loop reads it, decoupled from updated_at).
    last_event_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    # One-shot stalled-alert marker (operator-visible; NOT a terminal state;
    # cleared when the next event arrives).
    stalled_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )


class ExecutionLogFile(Base):
    """Log index/offset/status row. Bodies live on disk, NOT in PostgreSQL.

    Primary key is ``(task_id, execution_id, stream)``. These are wire/disk
    identifiers: ``task_id`` holds the parent :class:`Task` id and
    ``execution_id`` holds the atomic :class:`Execution` id — they match the agent
    wire and the on-disk ``{task_id}/{execution_id}.log`` path.
    """

    __tablename__ = "execution_log_files"

    task_id: Mapped[str] = mapped_column(String(32), primary_key=True)
    execution_id: Mapped[str] = mapped_column(String(32), primary_key=True)
    # log | stdout | stderr | system (scrapy only produces "log")
    stream: Mapped[str] = mapped_column(
        String, primary_key=True, default="log"
    )
    storage_path: Mapped[str] = mapped_column(String, nullable=False)
    size_bytes: Mapped[int] = mapped_column(
        BigInteger, nullable=False, default=0
    )
    last_pulled_offset: Mapped[int] = mapped_column(
        BigInteger, nullable=False, default=0
    )
    # final_offset = server file PHYSICAL size (incl. visible gap markers);
    # agent logical consumption progress lives in last_pulled_offset (never mix).
    final_offset: Mapped[int | None] = mapped_column(BigInteger, nullable=True)
    # active | finalizing | complete | missing | expired  (log LIFECYCLE)
    status: Mapped[str] = mapped_column(
        String, nullable=False, default="active"
    )
    # Phase 1.5: log COMPLETENESS, decoupled from lifecycle status. Sticky:
    # once "partial" (a gap was seen), it never reverts to "complete".
    # complete | partial | missing | expired
    log_integrity: Mapped[str] = mapped_column(
        String, nullable=False, default="complete"
    )
    gap_count: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    first_gap_expected_offset: Mapped[int | None] = mapped_column(
        BigInteger, nullable=True
    )
    first_gap_actual_offset: Mapped[int | None] = mapped_column(
        BigInteger, nullable=True
    )
    started_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    finished_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    retained_until: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )


class BuildArtifact(Base):
    """The canonical product entity: an executable build artifact (phase 1.8).

    A build artifact is the *thing that runs* (not the build process). Phase 1.8
    only makes ``artifact_type="scrapy"`` / ``package_format="egg"`` runnable;
    ``python_wheel`` / ``docker_image`` are reserved type values, not executable.

    Dedup key for file artifacts is ``(artifact_type, content_hash)`` — for
    Scrapy that is the egg sha256. The legacy ``scrapy_artifacts`` table is kept
    as a deployment/cache registry and is NOT the canonical entity.

    ``artifact_metadata`` (JSONB column ``metadata`` would clash with the
    Declarative ``metadata`` attribute, so the column is named
    ``artifact_metadata``) carries type-specific data; for Scrapy:
    ``{"project", "version", "spiders", "fetch_path"}``.
    """

    __tablename__ = "build_artifacts"
    __table_args__ = (
        UniqueConstraint(
            "artifact_type", "content_hash", name="uq_build_artifacts_type_hash"
        ),
    )

    id: Mapped[str] = mapped_column(String(32), primary_key=True, default=_new_id)
    # scrapy | python_wheel (reserved) | docker_image (reserved)
    artifact_type: Mapped[str] = mapped_column(String, nullable=False)
    # egg | wheel (reserved) | image (reserved)
    package_format: Mapped[str] = mapped_column(String, nullable=False)
    name: Mapped[str] = mapped_column(String, nullable=False)
    filename: Mapped[str | None] = mapped_column(String, nullable=True)
    # sha256 for file artifacts (Scrapy egg). NULL for non-file/reserved types.
    content_hash: Mapped[str | None] = mapped_column(String, nullable=True, index=True)
    size_bytes: Mapped[int] = mapped_column(
        BigInteger, nullable=False, default=0
    )
    artifact_metadata: Mapped[dict] = mapped_column(
        _JSON, nullable=False, default=dict
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )


class ScrapyArtifact(Base):
    """A deployed (uploaded) Scrapy egg and where it was deployed.

    Legacy deployment/cache registry (phase 1). The canonical product entity is
    :class:`BuildArtifact`; this table is kept readable, not renamed in place.
    """

    __tablename__ = "scrapy_artifacts"

    id: Mapped[str] = mapped_column(String(32), primary_key=True, default=_new_id)
    project: Mapped[str] = mapped_column(String, nullable=False)
    version: Mapped[str] = mapped_column(String, nullable=False)
    filename: Mapped[str] = mapped_column(String, nullable=False)
    sha256: Mapped[str] = mapped_column(String, nullable=False)
    size_bytes: Mapped[int] = mapped_column(
        BigInteger, nullable=False, default=0
    )
    agent_id: Mapped[str | None] = mapped_column(String, nullable=True)
    endpoint: Mapped[str | None] = mapped_column(String, nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
