"""server -> agent execution-control protocol (phase 1).

These schemas describe the HTTP contract the server uses to drive a dopilot
agent over its root API (no ``/api/v1`` prefix): run a Scrapy job, stop it,
poll its status, deploy a pre-built egg, and clean up its logs.

The agent is **stateless w.r.t. log offsets** (offset authority is the server's
PostgreSQL ``execution_log_files.last_pulled_offset``); these schemas carry only
what the agent needs to act. Log byte-slice pulls use :class:`TailRequest` /
:class:`TailResponse` from :mod:`dopilot_protocol.logs`.
"""

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import BaseModel, Field


class AttemptStatus(str, Enum):
    """Lifecycle state of a single execution attempt as the agent reports it.

    This is the agent-observed status (derived from local scrapyd). The server
    maps it onto its own richer execution/log state machine
    (queued/running/finalizing/complete/failed/canceled/lost).
    """

    pending = "pending"
    running = "running"
    finished = "finished"
    failed = "failed"
    canceled = "canceled"
    unknown = "unknown"


class AgentRunRequest(BaseModel):
    """server -> agent ``POST /run``: launch one Scrapy job via local scrapyd.

    ``execution_id`` / ``attempt_id`` are generated by the server and are the
    stable identity used for log addressing and state-file naming on the agent.
    ``version=None`` means "use the latest deployed version" of ``project``.
    """

    execution_id: str
    attempt_id: str
    project: str
    spider: str
    version: str | None = None
    settings: dict[str, str] = Field(default_factory=dict)
    args: dict[str, str] = Field(default_factory=dict)
    task_type: str = "scrapy"


class AgentRunResponse(BaseModel):
    """agent -> server: acknowledges a launched job with its scrapyd job id."""

    execution_id: str
    attempt_id: str
    remote_job_id: str
    status: AttemptStatus = AttemptStatus.running


class AgentStopRequest(BaseModel):
    """server -> agent ``POST /stop``: cancel one attempt (idempotent).

    Stopping an already-finished/unknown attempt is not an error: the response
    reports the resulting status with ``stopped=False``.
    """

    execution_id: str
    attempt_id: str


class AgentStopResponse(BaseModel):
    """agent -> server: outcome of a stop request."""

    execution_id: str
    attempt_id: str
    status: AttemptStatus
    stopped: bool = False
    detail: dict[str, Any] = Field(default_factory=dict)


class AgentStatusResponse(BaseModel):
    """agent -> server ``GET /status``: current attempt state.

    The server polls this to decide when to move an attempt into ``finalizing``
    and run the final log drain. ``status=unknown`` means the agent has a state
    mapping but can no longer determine liveness from scrapyd (e.g. job id
    absent after an agent restart).
    """

    execution_id: str
    attempt_id: str
    remote_job_id: str | None = None
    status: AttemptStatus
    exit_code: int | None = None
    detail: dict[str, Any] = Field(default_factory=dict)


class CleanupResponse(BaseModel):
    """agent -> server ``POST /executions/{attempt_id}/logs/cleanup``.

    Called by the server only after final drain + ``complete``. ``removed`` is
    True when the agent deleted the underlying ``job.log`` (and state file);
    idempotent re-calls return ``removed=False`` once already cleaned.
    """

    attempt_id: str
    removed: bool = False
    detail: dict[str, Any] = Field(default_factory=dict)


class EggDeployResponse(BaseModel):
    """agent -> server ``POST /artifacts/scrapy/egg``: scrapyd addversion result.

    ``spiders`` is the spider list scrapyd reports after deploying the egg.
    """

    project: str
    version: str
    spiders: list[str] = Field(default_factory=list)
    detail: dict[str, Any] = Field(default_factory=dict)
