"""server -> agent execution-control protocol (phase 1, **LEGACY HTTP path**).

These schemas described the HTTP contract the server used to drive a dopilot
agent over its root API in phase 1: run a Scrapy job, stop it, poll its status,
deploy a pre-built egg, and clean up its logs.

Phase 1.5 (``docs/refactor/00-redis-streams-agent-communication.md``) replaces
the run/status/stop/cleanup main paths with Redis Streams — see
:mod:`dopilot_protocol.streams`. The types here are retained as **legacy**:
``AttemptStatus`` and ``AgentRunRequest`` are still reused (the latter as the
``run`` command payload shape, the former as the agent-observed status enum).
``AgentRunResponse`` / ``AgentStopResponse`` / ``AgentStatusResponse`` are kept
as the in-process runner result shapes but no longer represent a live HTTP path.

Phase 2.2.7 removed the agent's inbound egg-deploy HTTP endpoint (eggs are now
fetched from the server by the agent during Redis command execution), so the old
``EggDeployResponse`` schema was dropped — it had no remaining producer/consumer.

Naming (phase 2a clean-cut): ``task_id`` is ``Task.id`` and ``execution_id`` is
the atomic ``Execution.id`` — the same names as the Redis wire and the server
domain.

On offsets: the agent now actively **publishes** log increments carrying a
logical byte ``offset`` (:class:`dopilot_protocol.streams.AgentLogEvent`); the
server's ``execution_log_files.last_pulled_offset`` remains the consumption-
progress authority. The agent does not hold the server's final offset authority.
"""

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import BaseModel, Field


class AttemptStatus(str, Enum):
    """Lifecycle state of a single execution attempt as the agent reports it.

    This is the agent-observed status (derived from local scrapyd). The server
    maps it onto its own richer execution/log state machine
    (queued/running/finalizing/complete/failed/canceled/lost).
    """

    pending = "pending"
    running = "running"
    finished = "finished"
    failed = "failed"
    canceled = "canceled"
    unknown = "unknown"


class AgentRunRequest(BaseModel):
    """server -> agent ``POST /run``: launch one Scrapy job via local scrapyd.

    ``task_id`` / ``execution_id`` are generated by the server and are the
    stable identity used for log addressing and state-file naming on the agent.
    ``version=None`` means "use the latest deployed version" of ``project``.
    """

    task_id: str
    execution_id: str
    project: str
    spider: str
    version: str | None = None
    settings: dict[str, str] = Field(default_factory=dict)
    args: dict[str, str] = Field(default_factory=dict)
    task_type: str = "scrapy"


class AgentRunResponse(BaseModel):
    """agent -> server: acknowledges a launched job with its scrapyd job id."""

    task_id: str
    execution_id: str
    remote_job_id: str
    status: AttemptStatus = AttemptStatus.running


class AgentStopResponse(BaseModel):
    """agent -> server: outcome of a stop request."""

    task_id: str
    execution_id: str
    status: AttemptStatus
    stopped: bool = False
    detail: dict[str, Any] = Field(default_factory=dict)


class AgentStatusResponse(BaseModel):
    """agent -> server: current attempt state.

    The server polls this to decide when to move an attempt into ``finalizing``
    and run the final log drain. ``status=unknown`` means the agent has a state
    mapping but can no longer determine liveness from scrapyd (e.g. job id
    absent after an agent restart).
    """

    task_id: str
    execution_id: str
    remote_job_id: str | None = None
    status: AttemptStatus
    exit_code: int | None = None
    detail: dict[str, Any] = Field(default_factory=dict)
